{{- if .Values.external_dns.enabled -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: external-dns
  namespace: {{ .Release.Namespace }}
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.opensource.zalan.do/teapot/external-dns:{{ .Values.external_dns.tag }}
        args:
        - --source=ingress
        - --domain-filter={{ .Values.ingress.dns_zone }} # will make ExternalDNS see only the hosted zones matching provided domain, omit to process all available hosted zones
        - --provider=aws
        - --policy=upsert-only # would prevent ExternalDNS from deleting any records, omit to enable full synchronization
        - --aws-zone-type=public # only look at public hosted zones (valid values are public, private or no value for both)
        - --registry=txt
        - --txt-owner-id=my-identifier
{{- end -}}